#!/bin/sh

if [ -z "${EXAMPLE_HOME}" ]
then
  echo "EXAMPLE_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${EXAMPLE_HOME}/lib" \
-m com.io7m.bugs.simplejavamail/com.io7m.bugs.simplejavamail.Main \
"$@"
